import { jsPDF } from "jspdf";
import PDF from "../PDF";

export default function ExportPDF({ formData, customFields, fields }) {
  const generatePDF = () => {
    // Filter out empty fields
    const filledFields = [];

    // Add filled standard fields
    fields.forEach((field) => {
      const value = formData[field.key];
      if (value && value.trim()) {
        filledFields.push({ label: field.label, value: value });
      }
    });

    // Add filled custom fields
    if (customFields && customFields.length > 0) {
      customFields.forEach((field) => {
        if (field.value && field.value.trim()) {
          filledFields.push({ label: field.labelKeyword, value: field.value });
        }
      });
    }

    // Check if there's any data to export
    if (filledFields.length === 0) {
      alert("No data to export. Please fill in some fields first.");
      return;
    }

    // Create PDF
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const maxWidth = pageWidth - 2 * margin;
    let yPosition = margin;

    // Helper function to add new page if needed
    const checkAddPage = (requiredSpace) => {
      if (yPosition + requiredSpace > pageHeight - margin) {
        doc.addPage();
        yPosition = margin;
        return true;
      }
      return false;
    };

    // Metadata
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 100, 100);

    const date = new Date();
    const formattedDate = date.toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
    const formattedTime = date.toLocaleTimeString("en-US");

    doc.text(
      `Exported on: ${formattedDate} at ${formattedTime}`,
      margin,
      yPosition
    );
    yPosition += 5;
    doc.text(`Total Fields: ${filledFields.length}`, margin, yPosition);
    yPosition += 10;

    // Draw horizontal line
    doc.setDrawColor(0, 0, 0);
    doc.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 10;

    // Fields
    filledFields.forEach((field, index) => {
      doc.setTextColor(0, 0, 0);

      // Check if we need a new page for this field
      checkAddPage(30);

      // Field label
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(100, 100, 100);
      doc.text(field.label.toUpperCase(), margin, yPosition);
      yPosition += 6;

      // Field value
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(0, 0, 0);

      // Split text if it's too long
      const lines = doc.splitTextToSize(field.value, maxWidth);
      lines.forEach((line) => {
        checkAddPage(6);
        doc.text(line, margin, yPosition);
        yPosition += 6;
      });

      yPosition += 8;
    });

    // Footer
    checkAddPage(20);
    yPosition = pageHeight - margin;
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(150, 150, 150);
    doc.text(
      "Generated by Google Form Autofill Extension",
      pageWidth / 2,
      yPosition,
      { align: "center" }
    );

    // Save PDF
    doc.save(`google-form-profile-${date.toISOString().split("T")[0]}.pdf`);
  };

  return (
    <button
      onClick={generatePDF}
      className="w-full py-2.5 px-3 rounded-lg border border-[#e2e8f0] text-[12px] font-medium cursor-pointer transition-all duration-200 bg-white text-[#0f172a] hover:bg-[#f0f0f0] hover:border-[#0f172a] flex items-center justify-start gap-2.5"
    >
      <PDF />
      export as PDF
    </button>
  );
}
